"""Azure OpenAI model configurations.

Deployment names match the standard OpenAI model names so that
the same model references work transparently across providers.
"""
from ..llm_provider_models import LLMInfo, ModelSize, ReasoningEffort


AZURE_OPENAI_MODELS = [
    # --- GPT-5.4 ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5.4",
        label="GPT-5.4",
        model="gpt-5.4",  # deployment name
        description="Most capable frontier model with unified reasoning, vision, and tool use.",
        input_token_price=2.50,
        cached_input_token_price=0.25,
        output_token_price=15.00,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.LARGE,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=100,
        speed=7,
        quality=10,
        best_use="General purpose",
        highlights=["Reasoning", "Images", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- GPT-5.4 Large Context (1M tokens) ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5.4-large-ctx",
        label="GPT-5.4 Large Context",
        model="gpt-5.4",  # same deployment, pricing differs above 272K
        description="GPT-5.4 with 1M token context window. Higher per-token cost.",
        input_token_price=5.00,
        cached_input_token_price=0.50,
        output_token_price=22.50,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.LARGE,
        max_input_tokens=1000000,
        max_output_tokens=128000,
        popularity=35,
        speed=5,
        quality=10,
        best_use="Large documents",
        highlights=["1M context", "Reasoning", "Images", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- GPT-5 Mini ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5-mini",
        label="GPT-5 Mini",
        model="gpt-5-mini",
        description="Fast and capable model for general chat and tool calling.",
        input_token_price=0.40,
        cached_input_token_price=0.10,
        output_token_price=1.60,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.MEDIUM,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=85,
        speed=9,
        quality=7,
        best_use="Quick tasks",
        highlights=["Fast", "Images", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- GPT-5 Nano ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5-nano",
        label="GPT-5 Nano",
        model="gpt-5-nano",
        description="Fastest, most cost-effective model for low-latency tasks.",
        input_token_price=0.10,
        cached_input_token_price=0.025,
        output_token_price=0.40,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.SMALL,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=60,
        speed=10,
        quality=5,
        best_use="Low-latency tasks",
        highlights=["Fastest", "Low cost"],
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
]
